"""empty message

Revision ID: 181bc589f4e6
Revises: 4b4071da9442
Create Date: 2021-04-23 12:31:07.285444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181bc589f4e6'
down_revision = '4b4071da9442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=35), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('viagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=True),
    sa.Column('motorista_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['estado_id'], ['estado.id'], ),
    sa.ForeignKeyConstraint(['motorista_id'], ['motorista.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_foreign_key(None, 'posicao', 'viagem', ['viagem_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posicao', type_='foreignkey')
    op.drop_table('viagem')
    op.drop_table('estado')
    # ### end Alembic commands ###
