"""empty message

Revision ID: 3942b201a511
Revises: 
Create Date: 2021-05-10 15:52:49.719114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3942b201a511'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=35), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=25), nullable=True),
    sa.Column('cpf', sa.String(length=25), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=25), nullable=False),
    sa.Column('celular', sa.String(length=25), nullable=False),
    sa.Column('sexo', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('id')
    )
    op.create_table('tipo_uber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('multiplicador', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('motorista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('carro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=25), nullable=True),
    sa.Column('chassi', sa.String(length=25), nullable=False),
    sa.Column('marca', sa.String(length=25), nullable=False),
    sa.Column('placa', sa.String(length=25), nullable=False),
    sa.Column('ano', sa.String(length=25), nullable=False),
    sa.Column('cor', sa.String(length=25), nullable=False),
    sa.Column('tipo_uber_id', sa.Integer(), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['motorista_id'], ['motorista.id'], ),
    sa.ForeignKeyConstraint(['tipo_uber_id'], ['tipo_uber.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('cartao_de_credito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=25), nullable=False),
    sa.Column('cvv', sa.Integer(), nullable=False),
    sa.Column('data_validade', sa.String(length=25), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('viagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['estado_id'], ['estado.id'], ),
    sa.ForeignKeyConstraint(['motorista_id'], ['motorista.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('metodo_pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=35), nullable=False),
    sa.Column('viagem_id', sa.Integer(), nullable=False),
    sa.Column('cartao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cartao_id'], ['cartao_de_credito.id'], ),
    sa.ForeignKeyConstraint(['viagem_id'], ['viagem.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('posicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('viagem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['viagem_id'], ['viagem.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posicao')
    op.drop_table('metodo_pagamento')
    op.drop_table('viagem')
    op.drop_table('cartao_de_credito')
    op.drop_table('carro')
    op.drop_table('motorista')
    op.drop_table('cliente')
    op.drop_table('tipo_uber')
    op.drop_table('pessoa')
    op.drop_table('estado')
    # ### end Alembic commands ###
