"""empty message

Revision ID: 45786f0644a8
Revises: 98e21db80456
Create Date: 2021-04-22 17:01:58.558026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45786f0644a8'
down_revision = '98e21db80456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_uber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('multiplicador', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=25), nullable=True),
    sa.Column('tipo_uber_id', sa.Integer(), nullable=False),
    sa.Column('chassi', sa.String(length=25), nullable=False),
    sa.Column('marca', sa.String(length=25), nullable=False),
    sa.Column('placa', sa.String(length=25), nullable=False),
    sa.Column('ano', sa.String(length=25), nullable=False),
    sa.Column('cor', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['tipo_uber_id'], ['tipo_uber.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('tipo_uber_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carro')
    op.drop_table('tipo_uber')
    # ### end Alembic commands ###
