"""empty message

Revision ID: 47146efc8420
Revises: a2ff4843bc49
Create Date: 2021-04-22 23:12:24.741709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47146efc8420'
down_revision = 'a2ff4843bc49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viagem')
    # ### end Alembic commands ###
