"""empty message

Revision ID: 4b4071da9442
Revises: d8332ea84cf9
Create Date: 2021-04-23 12:16:19.262604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b4071da9442'
down_revision = 'd8332ea84cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'posicao', ['id'])
    op.add_column('viagem', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.add_column('viagem', sa.Column('motorista_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'viagem', ['id'])
    op.create_foreign_key(None, 'viagem', 'motorista', ['motorista_id'], ['id'])
    op.create_foreign_key(None, 'viagem', 'cliente', ['cliente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'viagem', type_='foreignkey')
    op.drop_constraint(None, 'viagem', type_='foreignkey')
    op.drop_constraint(None, 'viagem', type_='unique')
    op.drop_column('viagem', 'motorista_id')
    op.drop_column('viagem', 'cliente_id')
    op.drop_constraint(None, 'posicao', type_='unique')
    # ### end Alembic commands ###
