"""empty message

Revision ID: 53420368dff6
Revises: 45786f0644a8
Create Date: 2021-04-22 17:45:27.261436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53420368dff6'
down_revision = '45786f0644a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('carro_tipo_uber_id_key', 'carro', type_='unique')
    op.create_unique_constraint(None, 'carro', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carro', type_='unique')
    op.create_unique_constraint('carro_tipo_uber_id_key', 'carro', ['tipo_uber_id'])
    # ### end Alembic commands ###
