"""empty message

Revision ID: 6a00f6d138f3
Revises: dba08449858e
Create Date: 2021-04-22 16:09:15.438559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a00f6d138f3'
down_revision = 'dba08449858e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('chassi', sa.String(), nullable=True),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('placa', sa.String(), nullable=True),
    sa.Column('ano', sa.String(), nullable=True),
    sa.Column('cor', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carro')
    # ### end Alembic commands ###
