"""empty message

Revision ID: 6b727e2c8d79
Revises: 76f6d21cff5c
Create Date: 2021-04-25 12:13:53.494398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b727e2c8d79'
down_revision = '76f6d21cff5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('viagem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['viagem_id'], ['viagem.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posicao')
    # ### end Alembic commands ###
