"""empty message

Revision ID: 75edf50e41a9
Revises: 181bc589f4e6
Create Date: 2021-04-25 12:05:52.829798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75edf50e41a9'
down_revision = '181bc589f4e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'estado', ['id'])
    op.create_unique_constraint(None, 'viagem', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'viagem', type_='unique')
    op.drop_constraint(None, 'estado', type_='unique')
    # ### end Alembic commands ###
