"""empty message

Revision ID: 76f6d21cff5c
Revises: 75edf50e41a9
Create Date: 2021-04-25 12:12:52.116236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f6d21cff5c'
down_revision = '75edf50e41a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('viagem', 'estado_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('viagem', 'estado_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
