"""empty message

Revision ID: 7fad3e9b01a9
Revises: d02dabd65124
Create Date: 2021-04-22 23:20:11.660344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7fad3e9b01a9'
down_revision = 'd02dabd65124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viagem', sa.Column('cliente_id', sa.Integer(), nullable=False))
    op.add_column('viagem', sa.Column('motorista_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'viagem', 'cliente', ['cliente_id'], ['id'])
    op.create_foreign_key(None, 'viagem', 'motorista', ['motorista_id'], ['id'])
    op.drop_column('viagem', 'longitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viagem', sa.Column('longitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'viagem', type_='foreignkey')
    op.drop_constraint(None, 'viagem', type_='foreignkey')
    op.drop_column('viagem', 'motorista_id')
    op.drop_column('viagem', 'cliente_id')
    # ### end Alembic commands ###
