"""empty message

Revision ID: 972e704c3b79
Revises: c48b61e3f59b
Create Date: 2021-04-22 13:14:39.256941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '972e704c3b79'
down_revision = 'c48b61e3f59b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carro', sa.Column('cor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carro', 'cor')
    # ### end Alembic commands ###
