"""empty message

Revision ID: 98e21db80456
Revises: b8868e0714a5
Create Date: 2021-04-22 16:52:20.446204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e21db80456'
down_revision = 'b8868e0714a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carro', sa.Column('tipo_uber_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'carro', 'tipo_uber', ['tipo_uber_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carro', type_='foreignkey')
    op.drop_column('carro', 'tipo_uber_id')
    # ### end Alembic commands ###
