"""empty message

Revision ID: 9d2df03b1d09
Revises: fd4a5ab1e04f
Create Date: 2021-04-22 22:34:36.474176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d2df03b1d09'
down_revision = 'fd4a5ab1e04f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=25), nullable=True),
    sa.Column('cpf', sa.String(length=25), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=25), nullable=False),
    sa.Column('celular', sa.String(length=25), nullable=False),
    sa.Column('sexo', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'carro', ['placa'])
    op.create_unique_constraint(None, 'motorista', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'motorista', type_='unique')
    op.drop_constraint(None, 'carro', type_='unique')
    op.drop_table('cliente')
    # ### end Alembic commands ###
