"""empty message

Revision ID: a2ff4843bc49
Revises: bae8673df88e
Create Date: 2021-04-22 23:11:36.971517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ff4843bc49'
down_revision = 'bae8673df88e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'posicao', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posicao', type_='unique')
    # ### end Alembic commands ###
