"""empty message

Revision ID: c48b61e3f59b
Revises: 43fae9d80303
Create Date: 2021-04-22 13:06:50.799059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c48b61e3f59b'
down_revision = '43fae9d80303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('chassi', sa.String(), nullable=True),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('placa', sa.String(), nullable=True),
    sa.Column('ano', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carro')
    # ### end Alembic commands ###
