"""empty message

Revision ID: fd4a5ab1e04f
Revises: 53420368dff6
Create Date: 2021-04-22 18:11:30.481900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd4a5ab1e04f'
down_revision = '53420368dff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motorista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=25), nullable=True),
    sa.Column('carro_id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=25), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=25), nullable=False),
    sa.Column('celular', sa.String(length=25), nullable=False),
    sa.Column('sexo', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['carro_id'], ['carro.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('motorista')
    # ### end Alembic commands ###
